remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: My WildCat Studios Portfolio 
description: >-
         This is my portfolio showcasing my projects and skills.
baseurl: "" # leave empty since this is your user page
url: "https://NM1333101.github.io" # replace YOURUSERNAME with your GitHub username
theme: jekyll-theme-minima # replace with your chosen theme from the list
